language: julia
os:
  - linux
  - osx
sudo: required
git:
  depth: 3 
julia:
  - 0.5
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("QuantumLab")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
# uncomment the following lines to override the default test script
#script:
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd(),"QuantumLab"); Pkg.build("QuantumLab"); Pkg.test("QuantumLab"; coverage=true)'
